apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: myhttpd
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploymypage
spec:
  replicas: 3
  selector:
    matchLabels:
       env: deploy
  template:
    metadata:
     name: myweb-pod
     labels:
       env: deploy
    spec: 
      containers:
        - name: web
          image: httpd
          volumeMounts:
            - name: logs
              mountPath: /etc/httpd/logs/
          volumeMounts:
            - name: volume
              mountPath: /usr/local/apache2/htdocs/ 
      volumes:
      - name: logs
        persistentVolumeClaim:
            claimName: pvc
      - name: volume
        persistentVolumeClaim:
            claimName: myhttpd